apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRESQL_DATABASE: llamastack
  POSTGRESQL_USER: llamastack
  POSTGRESQL_PASSWORD: llamastack
