apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
stringData:
  POSTGRESQL_DATABASE: ps_db
  POSTGRESQL_USER: ps_user
  POSTGRESQL_PASSWORD: SecurePassword
